name: build

on: [push, pull_request]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Checkout qwc-docker
        uses: actions/checkout@master
        with:
          repository: qwc-services/qwc-docker
          path: qwc-docker

      - name: Start required services
        run: |
          cd qwc-docker
          sed -i 's|qwc-solr:|localhost:|' volumes/config/default/searchConfig.json
          sed -Ei "s|^(\s*POSTGRES_PASSWORD:).*$|\1 'waej7WuoOoth0wor'|" docker-compose-example.yml
          # This is needed, because solr generates files and needs permissions to store them
          # in volumes/solr/*
          chmod 777 -R volumes/solr/
          docker compose -f docker-compose-example.yml up -d qwc-solr qwc-postgis

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Run unittests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          PYTHONPATH=$PWD/src CONFIG_PATH=$PWD/tests/config/ DB_URL=postgresql://qwc_admin:qwc_admin@localhost:5439/qwc_services FLASK_DEBUG=1 python test.py

      - name: Validate schema
        run: |
          python -m pip install check-jsonschema
          check-jsonschema --check-metaschema schemas/qwc-search-service.json

    build:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ endsWith(github.ref, '-lts') }} = true ]; then
            echo "tag=latest-lts,latest-${GITHUB_REF:11:4}-lts,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          else
            echo "tag=latest,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          fi

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.event_name != 'pull_request'
        with:
          name: sourcepole/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
